// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PatientInformationsAPI.Model;

#nullable disable

namespace PatientInformationsAPI.Migrations
{
    [DbContext(typeof(PatientInformationContext))]
    partial class PatientInformationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PatientInformationsAPI.Model.AllergiesDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AllergieId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModifierDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AllergieId");

                    b.HasIndex("PatientId");

                    b.ToTable("Allergies_Details", (string)null);
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.Allergy", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifierDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("Allergies");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.DiseaseInformation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifierDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("DiseaseInformations");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.Ncd", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifierDate")
                        .HasColumnType("datetime");

                    b.HasKey("Id");

                    b.ToTable("NCDs", (string)null);
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.NcdDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("ModifierDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Ncdid")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("NCDId");

                    b.Property<string>("PatientId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Ncdid");

                    b.HasIndex("PatientId");

                    b.ToTable("NCD_Details", (string)null);
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.PatientInformation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("DiseaseId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Epliepsy")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActve")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifierDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DiseaseId");

                    b.ToTable("PatientInformations");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.AllergiesDetail", b =>
                {
                    b.HasOne("PatientInformationsAPI.Model.Allergy", "Allergie")
                        .WithMany("AllergiesDetails")
                        .HasForeignKey("AllergieId")
                        .IsRequired()
                        .HasConstraintName("FK_Allergies_Details_Allergies");

                    b.HasOne("PatientInformationsAPI.Model.PatientInformation", "Patient")
                        .WithMany("AllergiesDetails")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_Allergies_Details_PatientInformations");

                    b.Navigation("Allergie");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.NcdDetail", b =>
                {
                    b.HasOne("PatientInformationsAPI.Model.Ncd", "Ncd")
                        .WithMany("NcdDetails")
                        .HasForeignKey("Ncdid")
                        .IsRequired()
                        .HasConstraintName("FK_NCD_Details_NCDs");

                    b.HasOne("PatientInformationsAPI.Model.PatientInformation", "Patient")
                        .WithMany("NcdDetails")
                        .HasForeignKey("PatientId")
                        .IsRequired()
                        .HasConstraintName("FK_NCD_Details_PatientInformations");

                    b.Navigation("Ncd");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.PatientInformation", b =>
                {
                    b.HasOne("PatientInformationsAPI.Model.DiseaseInformation", "Disease")
                        .WithMany("PatientInformations")
                        .HasForeignKey("DiseaseId")
                        .IsRequired()
                        .HasConstraintName("FK_PatientInformations_DiseaseInformations");

                    b.Navigation("Disease");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.Allergy", b =>
                {
                    b.Navigation("AllergiesDetails");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.DiseaseInformation", b =>
                {
                    b.Navigation("PatientInformations");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.Ncd", b =>
                {
                    b.Navigation("NcdDetails");
                });

            modelBuilder.Entity("PatientInformationsAPI.Model.PatientInformation", b =>
                {
                    b.Navigation("AllergiesDetails");

                    b.Navigation("NcdDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
